# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors                 = ["John Simpson"]
language                = "en"
multilingual            = false
src                     = "src"
title                   = "Template"

[output.html]
additional-css          = [ "section-lines.css" , "version-commit.css" ]
curly-quotes            = false
git-repository-url      = "https://github.com/kg4zow/mdbook-template"
no-section-label        = true
default-theme           = "rust"
preferred-dark-theme    = "ayu"

[preprocessor.version-commit]
renderers           = [ "html" ]
command             = "./version-commit"
