[book]
authors         = ["John Simpson"]
language        = "en"
multilingual    = false
src             = "src"
title           = "New Book"

[output.html]
additional-css  = [ "section-lines.css" , "version-commit.css" ]

[preprocessor.version-commit]
renderers       = [ "html" ]
#command         = """sh -c 'jq ".[1]"; ./version-commit theme/index-template.hbs > theme/index.hbs'"""
command         = "./version-commit"
