# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors                 = ["John Simpson"]
language                = "en"
src                     = "src"
title                   = "Template"

[output.html]
additional-css          = [ "section-lines.css" , "version-commit.css" ]
git-repository-url      = "https://github.com/kg4zow/mdbook-template"
no-section-label        = true
default-theme           = "rust"
preferred-dark-theme    = "ayu"
smart-punctuation       = false
hash-files              = false
sidebar-header-nav      = false

[preprocessor.version-commit]
renderers               = [ "html" ]
command                 = "./version-commit"

[output.html.fold]
enable                  = true
level                   = 0
